### ISSUE TITLE
Init function doesn't execute callback

### ISSUE THREAD

**Issue by santiDotIO** [auctifera-josed/cordova-plugin-magtek#1]
The init function doesn't execute the callback function, other functions like `startScanningForPeripherals`, `getDiscoveredPeripherals` don't seem to execute. I'm trying to scan for an eDynamo device. What other details can I provide to help debug?

**Comment by kevinjung2** [comment]
Hey santi6291,
Just came across this plugin and was wondering if you ever got this plugin working as intended? I am going to try scanning without the plugin and see if I can use it to connect to the device for now, but if you figured something out I will try that.

**Comment by santiDotIO** [comment]
Not really, the plugin wasn't really stable with the SDK unfortunately and we moved in a different direction.

**Comment by kevinjung2** [comment]
Ah OK, is there any chance you remember what you ended up using instead?

**Comment by santiDotIO** [comment]
We ended up postponing that initiative and then when the pandemic hit it didn't make much sense at the time to invest time on it sadly. We did look into using [MagneFlex](https://www.magtek.com/services/magneflex) software and I remember it being pretty well supported but you're locked into using a windows based machine

**Comment by kevinjung2** [comment]
Ok thanks for the help!
